# Site settings
name: Upham web pages
email: nathan.upham@yale.edu
author: n8upham

keywords: phylogenetics, evolution, biogeography, mammals, rodents, macroevolution, macroecology, sustainability, conservation, teaching, mentorship
description: Web pages describing NSU's academic interests and research

baseurl: https://n8upham.github.io
url: https://n8u.org

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: UA-67863233-1
google_universal_analytics_cookiedomain: auto

# Twitter Cards
twitter_user: n8_upham
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
